repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: mypy
        name: mypy (strict)
        entry: uv run mypy --strict aiochainscan
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: pytest
        name: pytest (quick)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
